### ISSUE TITLE
Use mask on other images?

### ISSUE THREAD

**Issue by jessicaguo** [hiweller/countcolors#2]
Hi Hannah, I was hoping you could advise me on a problem I'm having that seems simple. 

I'd like to use the mask created with `sphericalRange()` to evaluate other images. The identified pixels are stored in `out$pixel.idx`. How can I convert these pixel addresses into a mask of 0's and 1's of the same dimension as the original image, and multiply with another image?

I tried manually populating an array with 0's, then converting to 1's if the address matches a row in `out$pixel.idx`, but too inefficient to be useful. Is there a simple solution I'm missing?

**Comment by hiweller** [comment]
Hi Jessica!

Good question, and something I really should have included in the original package...

I would do it similar to how you're describing, but without a for loop, like so (taken from the example for the `sphericalRange()` function documentation):

```
# load the library
library(countcolors)

# load the image
flowers <- jpeg::readJPEG(system.file("extdata", "flowers.jpg", package =
                                        "countcolors"))
# define center & run the function
center <- c(255, 75, 75) / 255
red_flowers <- sphericalRange(flowers,
                              center = center,
                              radius = 0.2, 
                              target.color = "turquoise")

# make an empty array
empty_array <- matrix(0,
                      nrow = nrow(flowers),
                      ncol = ncol(flowers))

# use pixel.idx as an index for the array - no for loops needed
empty_array[red_flowers$pixel.idx] <- 1

# plot to make sure it worked:
plot(0:1, 0:1, type = "n", ann = F, axes = F,
     asp = nrow(flowers) / ncol(flowers))
rasterImage(empty_array, 0, 0, 1, 1)
```
This gets me a binary image like this:
![image](https://user-images.githubusercontent.com/12073558/186542959-7da8b367-3db6-4a58-8b6c-6c41f615518f.png)

Let me know if that helps, or if that's too slow of a solution. There are probably faster things to do that would require slightly fancier footwork here.
